server:
  port: 8080

market:
  datasetPath: "classpath:House Price Dataset.csv"
  cache:
    overviewTtl: PT5M
    csvTtl: PT10M
    overviewMaxSize: 200
    csvMaxSize: 100

predict:
  baseUrl: ${PREDICT_BASE_URL:http://8.136.196.64:8000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
